export enum ERROR_MESSAGE {
  GOOGLE_BAD_GATEWAY = "GOOGLE_BAD_GATEWAY",
  NOT_FOUND_EXCEPTION = "NOT_FOUND_EXCEPTION",
  IS_EXIST_USER = "IS_EXIST_USER",
  NO_AUTHRIZED_ERROR = "NO_AUTHRIZED_ERROR",
  TRANSACTION_FAILURE = "TRANSACTION_FAILURE",
}